config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "accept_order", to: 'pages#accept_order'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/stuff.rb
class Stuff < ApplicationRecord
  belongs_to :users
  belongs_to :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :uniqueness, scope: {:email}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def accept_order

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="credits">
    <p>test</p>
  </div>
  <div class="contact">
    <p>contact: </p>
    <p>pierretienne.soury@gmail.com</p>
  </div>
  <div class="contact">
    <p>made with love by <a href="http://pesoury.xyz">Pierre-Etienne Soury</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="page">
      <%= yield %>
    </div>
    <div style="postion: relative;">

    </div>
    <%= render 'layouts/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/accept_order.html.erb
<div class="titles center">
  <h1>Now you need to decide which quest you'll follow.</h1>
</div>
<div class="ambiance-text">
  <p>When you were walking, a lot of peasants asked you for some help; of course, you said now, since you wanted to fight for fame, glory and to help REAL people (and also for gold, but nobody has to know).
  After a couple of days wandering with your newly acquired weapon (or no weapon if you're a man), you realize you'll definitely need that gold, and tant pis for the glory and fame. You start considering your options...</p>
</div>
<div class="choice-title center">
  <p>Which Quest will you follow?</p>
</div>
<div class="choices">
  <div class="choice">
    <p>Planting corn seeds nearby a dark swamp</p>
  </div>
  <div class="choice">
    <p>cutting trees in a thick forest</p>
  </div>
  <div class="choice">
    <p>guarding the brothel</p>
  </div>
  <div class="choice">
    <p>begging for money</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="titles center">
  <h1>Welcome, Heros!</h1>
  <h2>We were waiting for you...</h2>
</div>
<div class="ambiance-text">
  <p>You'll face many challenges during your quest, and only a sharp mind, a keen eye, quick reflexes and strong strikes will allow you to get out of it alive and victorious.</p>
  <p>So behold! Now is the time to take your first decision...</p>
  <div class="choice-title center">
    <p>Choose a weapon: </p>
  </div>
  <div class="choices">
    <div class="choice">
      <%= link_to "Badass Magic Scepter", accept_order_path %>
      <a href="#" >Magic Scepter</a>
    </div>
    <div class="choice">
      <a href="#" >Bow and Arrows</a>
    </div>
    <div class="choice">
      <a href="#" >Small Sharp Knives</a>
    </div>
    <div class="choice">
      <a href="#" >Big Double Edges Sword</a>
    </div>
    <div class="choice">
      <a href="#" >No weapon, my mind is the weapon</a>
    </div>
  </div>
</div>

app/views/pages/random_event.html.erb
<div class="titles center">
  <h1>On your way to achieve your mighty but shamefull quest...</h1>
</div>
<div class="ambiance-text">
  <p>You come accross a shady stranger, who offers you to look at some of the camelote he has, he thinks you're handsome, and wants your honest legendary warrior opinion about a powerful relic he recently acquired. You so follow him, and as you arrive near his carriage, he opens his cape and your gaze is capted by a strange blue mirror... and you feel like you can't resist, you dive into the mirror.</p>
  <p>You just have time to grab something from the world you are before jumping into the Unknown</p>

</div>
<div class="choice-title center">
  <p>What item will you take with you?</p>
</div>
<div class="choices">
  <div class="choice">
    <p>the Merchant's gold, hanging by his belt</p>
  </div>
  <div class="choice">
    <p>A handful of grass and dirt, it's all you need</p>
  </div>
  <div class="choice">
    <p>A random jewellry from the Merchant's pocket</p>
  </div>
  <div class="choice">
  <%= link_to "The shady merchant himself", unknow_path %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>